import {Inter} from 'next/font/google';
import './globals.css';
import Link from 'next/link';
const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='layoutStyle'>
          <ul className='navClass center'>
            <li className='nav'>
              <Link href={'/'}>Home</Link>
            </li>
            <li className='nav'>
              <Link href={'/posts'}>Posts</Link>
            </li>
            <li className='nav'>
              <Link href={'/users'}>Users</Link>
            </li>
            <li className='nav'>
              <Link href={'/posts/new'}>Add Post</Link>
            </li>
            <li className='nav'>
              <Link href={'/users/new'}>Add User</Link>
            </li>
          </ul>
          {children}
        </main>
      </body>
    </html>
  );
}
